# Generated by Django 2.1.2 on 2018-10-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181004_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_edited',
        ),
    ]
